### ISSUE TITLE
Square brackets in Select option strings cause error

### ISSUE THREAD

**Issue by ividyon** [FRACerqueira/PromptPlus#57]
I tried doing the following:

```cs
    private static List<string> ConfigOptions()
    {
        List<string> list = new();

        list.Add(WitchyConfiguration.Bnd ? "[x] BND" : "[ ] BND");
        list.Add(WitchyConfiguration.Dcx ? "[x] DCX" : "[ ] DCX");

        return list;
    }

    public static void CliConfigMode(CliOptions opt)
    {
        var select = PromptPlus.Select<string>("Select");
        select.Interaction(ConfigOptions(), (select, s) => { select.AddItem(s); });
        select.Run();
    }
```

This led to the following error:

```
PPlus.PromptPlusException: Could not find color or style ''.
   at PPlus.Drivers.StyleParser.Parse(String text, Overflow overflow)
   at PPlus.Drivers.Segment.Parse(String text, Style style)
   at PPlus.Drivers.ConsoleDriveWindows.Write(String value, Nullable`1 style, Boolean clearrestofline)
   at PPlus.Controls.Objects.BaseControl`1.RenderBuffer()
   at PPlus.Controls.Objects.BaseControl`1.Start(CancellationToken stoptoken)
   at PPlus.Controls.Objects.BaseControl`1.Run(Nullable`1 stoptoken)
```

Removing the brackets from the strings fixed the problem.

P.S.: Is there a better way in PromptPlus to do toggleable checkboxes like this?

**Comment by FRACerqueira** [comment]
Hi , @ividyon 

Try it  (Double bracket):  list.Add(WitchyConfiguration.Bnd ? "[[x]] BND" : "[[ ]] BND");

P..S : Yes, The best option for this is the MultiSelect control.

See the usage examples in the Samples tab:

MultiSelectBasicSamples and MultiSelectUserScopeSamples
